-- CREATE TABLESPACE
CREATE TABLESPACE books_tb
DATAFILE '/oraclexe/data/mybooks.dbf'
SIZE 10M AUTOEXTEND ON NEXT 10K;

CREATE USER bookuser IDENTIFIED BY bookuser;
GRANT DBA to bookuser;

CREATE TABLE tbl_books (
    B_CODE	VARCHAR2(20),
    B_NAME	nVARCHAR2(125)	NOT NULL,	
    B_AUTHER	nVARCHAR2(125)	NOT NULL,	
    B_COMP	nVARCHAR2(125),		
    B_YEAR	VARCHAR2(10),		
    B_IPRICE	NUMBER,
    CONSTRAINT PK_BOOKS PRIMARY KEY(B_CODE)
);

CREATE TABLE tbl_read_book(
        RB_SEQ	NUMBER	NOT NULL,
        RB_BCODE	VARCHAR2(20)	NOT NULL,	
        RB_DATE	VARCHAR2(10)	NOT NULL,	
        RB_STIME	VARCHAR2(10),		
        RB_RTIME	NUMBER(10,3),		
        RB_SUBJECT	nVARCHAR2(20),		
        TB_TEXT	nVARCHAR2(400),		
        RB_STAR	NUMBER,		
        
        CONSTRAINT PK_READ_BOOKS PRIMARY KEY(RB_SEQ),
        CONSTRAINT FK_READ_BOOKS FOREIGN KEY (RB_BCODE)
        REFERENCES tbl_books(B_CODE)
        ON DELETE CASCADE
);


CREATE SEQUENCE SEQ_READ_BOOK
START WITH 1 INCREMENT BY 1;



DROP TABLE tbl_user ;
CREATE TABLE "TBL_USER" 
   (	"U_ID" VARCHAR2(125 BYTE) NOT NULL ENABLE, 
	"U_NICK" NVARCHAR2(125), 
	"U_NAME" NVARCHAR2(125) NOT NULL ENABLE, 
	"U_PASSWORD" VARCHAR2(125 BYTE) NOT NULL ENABLE, 
	"U_TEL" VARCHAR2(20 BYTE), 
	"U_GRADE" VARCHAR2(5 BYTE), 
	 PRIMARY KEY ("U_ID")
)